#!/bin/bash

while [ $# -gt 0 ]; do
    if [ "$1" = "-o" ]; then
        shift
        output_name="$1"
        shift
    else
        func+=("$1")
        shift
    fi
done

num_func=${#func[@]}

main_func="${func[$((num_func - 1))]}"

gcc -Wall -pedantic -Werror -Wextra -std=gnu89 "${func[@]}" -o "${output_name:-$(echo "$main_func" | rev | cut -d '.' -f 2- | rev)}"

