#!/bin/bash
read -e -p "Name of the test file: " test_file

read -e -p "Name of the function file: " func_file

gcc -Wall -pedantic -Werror -Wextra -std=gnu89 _putchar.c $test_file $func_file -o $(echo "$func_file" | rev | cut -d '.' -f 2- | rev)
