#!/bin/bash

error="Error:"
notice="Notice:"

force_flag=""
commit_msg=""

while [[ $# -gt 0 ]]; do
	case "$1" in
		-f)
			force_flag="-f"
			shift
			;;
		-m)
			shift
			commit_msg="$1"
			shift
			;;
		*)
			file_names+=("$1")
			shift
			;;
	esac
done

if [[ "${#file_names[@]}" -eq 0 ]]; then
	read -e -p "File name(s): " -a file_name
	IFS=' ' read -r -a file_names <<< "$file_name"
fi

if [[ ! "$force_flag" == "-f" ]]; then
	ignored_files=()

	for file_name in "${file_names[@]}"; do
		if git check-ignore -q "$file_name"; then
			ignored_files+=("$file_name")
		fi
	done

	if (( "${#ignored_files[@]}" > 0 )); then
		echo -e "\e[31m$error\e[0m The following files are ignored in .gitignore: ${ignored_files[*]}"
		echo -e "\e[36m$notice\e[0m Use '\e[33mpush -f\e[0m' to force push the ignored files"
		exit 0
	fi
fi

if [[ -z "$commit_msg" ]]; then
	read -e -p "What's your commit? : " commit_msg
fi

for file_name in "${file_names[@]}"; do
	if [[ "$force_flag" == "-f" ]]; then
		git add -f "$file_name"
	else
		git add "$file_name"
	fi
done

git commit -m "$commit_msg"
git push

